# Generated by Django 5.0.7 on 2024-07-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Название')),
                ('status', models.CharField(default='new', max_length=50, verbose_name='Статус')),
                ('date', models.DateField(max_length=50, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'db_table': 'tasks',
            },
        ),
    ]
